jobs:
  upload_HAR:
    name: Upload HAR file
    runs-on: ubuntu-latest
    steps:
      - name: Install JQ
        run: sudo apt-get install -y jq
      - name: Upload HAR Files to BrightSecurity Dashboard
        id: har-upload
        run: |
          mkdir hars
          cd hars
          wget https://gist.githubusercontent.com/DorShaer/037475d0febe67396d374a56d053e13e/raw/227b68d164051c024713fa5af7fa7cec7808af7d/brokencrystals.har -q
          for file in hars/*; do
            if [ -f "$file" ]; then
              echo "Processing file: $file"
              response=$(curl -F "file=@${file}" \
                -H "Authorization: Api-Key ${{ secrets.BRIGHT_TOKEN }}" \
                "https://app.brightsec.com/api/v1/projects/${{ secrets.BRIGHTSECURITY_PROJECT_ID }}/files")
              echo "Server response: $response"
              file_id=$(echo "$response" | jq -r '.id')
              echo "File ID: $file_id"
              echo "::set-output name=fileId::$file_id"
            fi
          done
